a.out:	main.o append_stu.o menu.o traverse_stu.o show_table.o delate_stu.o save_stu.o read_stu.o insert_stu.o  find_stu.o exit_stu.o sort_stu.o modief_stu.o getindex.o getindexs.o select_stu.o length_stu.o copy_stu.o logout.o getch.o
	gcc main.o append_stu.o menu.o traverse_stu.o show_table.o delate_stu.o save_stu.o read_stu.o insert_stu.o find_stu.o exit_stu.o sort_stu.o modief_stu.o getindex.o getindexs.o  select_stu.o length_stu.o copy_stu.o logout.o getch.o
main.o:main.c student.h
	gcc -c main.c
append_stu.o:append_stu.c student.h
	gcc -c append_stu.c
menu.o:menu.c student.h
	gcc -c menu.c
traverse_stu.o:traverse_stu.c student.h
	gcc -c traverse_stu.c
show_table.o:show_table.c student.h
	gcc -c show_table.c
delate_stu.o:delate_stu.c student.h
	gcc -c delate_stu.c
save_stu.o:save_stu.c student.h
	gcc -c save_stu.c
read_stu.o:read_stu.c student.h
	gcc -c read_stu.c
insert_stu.o:insert_stu.c student.h
	gcc -c insert_stu.c
find_stu.o:find_stu.c student.h
	gcc -c find_stu.c
exit_stu.o:exit_stu.c student.h
	gcc -c exit_stu.c
sort_stu.o:sort_stu.c student.h
	gcc -c sort_stu.c
modief_stu.o:modief_stu.c student.h
	gcc -c modief_stu.c
getindex.o:getindex.c student.h
	gcc -c getindex.c
length_stu.o:length_stu.c student.h
	gcc -c length_stu.c
copy_stu.o:copy_stu.c student.h
	gcc -c copy_stu.c
logout.o:logout.c student.h
	gcc -c logout.c
getch.o:getch.c student.h
	gcc -c getch.c
getindexs:getindexs.c student.h
	gcc -c getindexs.c
